### ISSUE TITLE
GoDBLedger Roadmap

### ISSUE THREAD

**Issue by darcys22** [darcys22/godbledger#169]
# Roadmap and Vision for GoDBLedger 

GoDBLedger was built on the assumption that accounting software globally is not making our business and individual finances easier. Incentives exist for the Accounting and Legal industries to bill expensive staff for financial work rather than build automated solutions and as a result the software of the industry has not kept up with the world. We believe that if the infrastructure was built for accounting industry, then almost the entire process from data entry to tax return lodgement can be automated. GoDBLedger aims to be at the core of this automated process with other software packages leveraging it to achieve this goal of financial automation

## Where we currently are

GoDBLedger currently runs well in the command line. The server runs fairly efficiently and and opens up a useful RPC port for scripts and software to sent transactions to. If a person is technical enough to wield a command line or a script this is useful, however this is not good enough for accountants and regular users. The next steps is to cater to the accounting and business person demographic.

### Short term - High Priority Features

- [ ] **Build GoDBLedger-web: Providing a GUI interface usable by non technical accountants/users.**
- [ ] Journal Entry Page
- [ ] Create Journal Entry
- [ ] Edit Journal Entry
- [ ] Reports Page
- [ ] Trial Balance Report
- [ ] General Ledger Report
- [ ] Export Reports to PDF, Excel, CSV
- [ ] Bank Reconciliation Page
- [ ] Bank Reconciliation Database
- [ ] Chart of Accounts Management Page
- [ ] Account Tagging and Management Page
- [ ] User Management Page
- [ ] Keep track of transactions posted with different users through private/public keys
- [ ] Profit and Loss Report
- [ ] Balance Sheet
- [ ] Docker scripts to run the server easily
- [ ] Aggressively test usability of the webserver (Important! make the MVP super user friendly before trying to tackle the harder features)

### Medium term Goals/ Features

- [ ] Build a hosting website to provide a paid option for GoDBLedger/GoDBLedger-web

### Other interesting features - Low Priority

- [ ] Yurnell - Programmable journal entries/ recurring scripts
- [ ] Cash Register App - Send transactions directly to GoDBLedger
- [ ] Graph Database Backend - Double entry transactions 

### Closing throughts

Financial software often ends up needing to do everything. If you build a general ledger suddenly it needs to do Payroll, Invoicing, Budgeting, Timesheets, Bank Reconciliation, Capital Gains Calculations, Tax and Compliance lodgement. These features are low priority until the core features listed above are tried and tested. Once we have a solid base to work on then we can tackle these bigger features

**Comment by mingsterism** [comment]
thanks for sharing the roadmap. really clarifies things. 
would like to ask if these features fit within the roadmap. 
1. integrating metabase. would this be part of the frontend? 
2. verified ledger transactions (can these be as metadata to each ledger transaction?)
  a. linked to a digital receipt as proof
  b. verified by bank reconciliation check

**Comment by darcys22** [comment]
Yep so metabase doesnt need integrating. It talks directly to to your database and our database is already accessable and easy to reason about. Its literally just install BI tool and point it at godbledgers db.

and the verified transactions is what the reconciliation table is for. We create a transaction for the bank feed/receipt that is external to our General Ledger and then when a GL transaction occurs for it we match it up! Then you can filter GL transactions by which ones match up to see what is reconciled and what isnt. This is already implemented, its at a point where i need to design a good interface for the reconciliations

**Comment by rukykf** [comment]
Hello @darcys22, I'd like to contribute but I figured it'd be a good idea to have some knowledge about the core domain of this project. I'm a software engineer but I've recently become fascinated with financial accounting and would like to become more acquainted with the domain. Are there any learning resources (books, video courses) that you could recommend for someone without an accounting background who's just looking to get enough knowledge to understand this domain? I've done some searching myself but there's a lot of resources and it's a bit difficult to make a choice on where to start, which is why I'd appreciate any recommendations you can share. Thanks!

**Comment by darcys22** [comment]
hi @rukykf there are a bunch of good articles that explain double entry bookkeeping for developers.

This has a lot of good content https://dev.to/kallmanation/double-entry-bookkeeping-for-programmers-3ok9 almost all of which is relevant in how godbledger is built

**Comment by rukykf** [comment]
Thanks for sharing @darcys22!
